config/routes.rb
Rails.application.routes.draw do

  get '/sitemap', to: redirect("https://#{ENV.fetch('S3_BUCKET_NAME')}.s3.amazonaws.com/sitemaps/sitemap.xml.gz")

  %w[about faqs affiliate_program terms privacy creator_appeal admin_action apply].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users' }
  get 'users/show'
  resources :users do
    resources :categorizations
    member do
      get :following, :followers
      get "change_role",  to: "users#change_role"
    end
  end
  resources :relationships
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'searches#search'
  get 'home', to: 'notes#home'
  resources :notes do
    collection do
      post :import
    end
    member do
      put "thank", to: "notes#vote"
      get "suggest", to: "notes#suggest"
      get "verify", to: "notes#verify"
      get "request_verification",  to: "notes#request_verification"
    end
    resources :questions, only: [:create, :destroy] do
      resources :answers, only: [:create, :destroy]
    end
  end
  resources :questions do
    member do
      put "vote", to: "questions#vote"
    end
    resources :answers, only: [:create, :edit, :update, :destroy] do
      put "vote", to: "answers#vote"
    end
  end
  resources :images, only: [:create, :destroy]
  root 'notes#home'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :note, optional: true
  belongs_to :user
  belongs_to :grade
  belongs_to :category
  belongs_to :chapter
  has_many :answers, dependent: :delete_all

  validates :content, presence: true

  acts_as_votable
  after_create :create_notifications

  include PgSearch
  pg_search_scope :search, against: [:content],
    using: {tsearch: {dictionary: 'english'}},
    associated_against: {user: :name, answers: :content}

  def to_param
    "#{id} class #{self.grade.name} #{self.category.name} question".parameterize
  end

  def top_ans
    self.answers.sort_by{ |answer| answer.get_upvotes.size }.last
  end

  def create_notifications
    if self.note.present?
      Notification.create(recipient: self.note.user, actor: self.user, action: 'questioned', notifiable: self.note)
    else
      User.admin.where(:category_id => self.category.id).each do |recipient|
        Notification.create(recipient: recipient, actor: self.user, action: 'asked', notifiable: self)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_parent, only: [:show, :create, :edit, :update, :destroy]

  respond_to :html
  respond_to :js

  def index
    params[:grade].present? ? @grade = params[:grade] : @grade = 'twelve'
    params[:category].present? ? @category = params[:category] : @category = 'physics'
    params[:chapter].present? ? @chapter = params[:chapter] : @chapter = 1

    @notes = Note.joins(:grade).where(grades: { name: @grade }).
                  joins(:category).where(categories: { name: @category }).
                  joins(:chapter).where(chapters: { id: @chapter }).
                  published.order("created_at ASC")
    @questions = Question.joins(:grade).where(grades: { name: @grade }).
                  joins(:category).where(categories: { name: @category }).
                  joins(:chapter).where(chapters: { id: @chapter }).
                  order("created_at ASC")

    set_meta_tags title: "Class #{@grade.humanize} #{@category.humanize}", site: 'Mattrab', description: "Browse high-quality notes, questions, and answers for #{Chapter.find(@chapter).name} of class #{@grade} #{@category} subject.", keywords: "Class #{@grade}, #{@category}, #{Chapter.find(@chapter).name}, notes for class #{@grade} #{@category}, notes for #{Chapter.find(@chapter).name}, question answer for class #{@grade} #{@category}",
                  og: { title: "Class #{@grade.humanize} #{@category.humanize}: #{Chapter.find(@chapter).name}", description: "Browse high-quality notes, questions, and answers for #{Chapter.find(@chapter).name} of class #{@grade} #{@category} subject.", type: 'website', url: notes_url(:grade=>"#{@grade}", :category=>"#{@category}", :chapter=>@chapter)},
                  twitter: { title: "Class #{@grade.humanize} #{@category.humanize}: #{Chapter.find(@chapter).name}", description: "Browse high-quality notes, questions, and answers for #{Chapter.find(@chapter).name} of class #{@grade} #{@category} subject." }
  end

  def show
    set_meta_tags title: @question.content.gsub(/<[^>]*>/, '').truncate(50), site: 'Mattrab', description: @question.content.gsub(/<[^>]*>/, '').truncate(150), keywords: "#{@question.chapter.name}, question on #{@question.chapter.name}, class #{@question.grade.name} #{@question.category.name} note, class #{@question.grade.name} questions, #{@question.chapter.name} questions", author: @question.user.name,
                  og: { title: @question.content.gsub(/<[^>]*>/, '').truncate(50), description: @question.content.gsub(/<[^>]*>/, '').truncate(150), type: 'website', url: question_url(@question) },
                  twitter: { title: @question.content.gsub(/<[^>]*>/, '').truncate(50), description: @question.content.gsub(/<[^>]*>/, '').truncate(150) }

    @question.update_attribute "view", @question.view += 1
    @answers = @question.answers.order(:cached_votes_up => :desc)
    respond_with(@answers)
  end

  def create
    if params[:note_id].present?
      params[:question][:content] = params[:question][:content].gsub('source', '<span>source</span>').gsub('position: fixed', '<span>position: fixed</span>').gsub('position:fixed', '<span>position:fixed</span>').gsub('method="delete"', '').gsub('link', '<span>link</span>').gsub('script', '<span>script</span>').gsub("method='delete'", '').gsub(/<iframe .*src="(https?:\/\/)?(?!(?:\/\/www.youtube.com\/embed\/|\/\/player.vimeo.com\/video\/)).*><\/iframe>/, '')
                                  .gsub('onerror', '<span>onerror</span>').gsub('onclick', '<span>onclick</span>').gsub('onload', '<span>onload</span>').gsub('onchange', '<span>onchange</span>').gsub('onmouseover', '<span>onmouseover</span>').gsub('onmouseout', '<span>onmouseout</span>').gsub('onmousedown', '<span>onmousedown</span>').gsub('onmouseup', '<span>onmouseup</span>').gsub('onfocus', '<span>onfocus</span>').gsub(/[\r\n]+/, ' ').html_safe
      @question = @note.questions.new(question_params)
      @question.user_id = current_user.id
      @question.grade_id = @note.grade.id
      @question.category_id = @note.category.id
      @question.chapter_id = @note.chapter.id
      @question.save
    else
      @question = current_user.questions.build(question_params)
      if @question.save
        redirect_to question_url(@question), notice: 'Question created successfully.'
      else
        render 'new'
      end
    end
  end

  def new
    @question = current_user.questions.build
  end

  def edit
    set_meta_tags title: 'Edit '+@question.content.gsub(/<[^>]*>/, '').truncate(50), site: 'Mattrab'
  end

  def update
    params[:question][:content] = params[:question][:content].gsub('source', '<span>source</span>').gsub('position: fixed', '<span>position: fixed</span>').gsub('position:fixed', '<span>position:fixed</span>').gsub('method="delete"', '').gsub('link', '<span>link</span>').gsub('script', '<span>script</span>').gsub("method='delete'", '').gsub(/<iframe .*src="(https?:\/\/)?(?!(?:\/\/www.youtube.com\/embed\/|\/\/player.vimeo.com\/video\/)).*><\/iframe>/, '')
                                .gsub('onerror', '<span>onerror</span>').gsub('onclick', '<span>onclick</span>').gsub('onload', '<span>onload</span>').gsub('onchange', '<span>onchange</span>').gsub('onmouseover', '<span>onmouseover</span>').gsub('onmouseout', '<span>onmouseout</span>').gsub('onmousedown', '<span>onmousedown</span>').gsub('onmouseup', '<span>onmouseup</span>').gsub('onfocus', '<span>onfocus</span>').gsub(/[\r\n]+/, ' ').html_safe
    if @question.update(question_params)
      redirect_to @question, notice: 'Question updated successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    if params[:note_id].present?
      @question = @note.questions.find(params[:id])
      @question.destroy
    else
      @question.destroy
      redirect_to questions_path, notice: 'Question deleted successfully.'
    end
  end

  def vote
    if !current_user.liked? @question
      @question.liked_by current_user
    else
      @question.unliked_by current_user
    end
    render :json => { :count => @question.get_upvotes.size }
  end

  private

  def question_params
    params.require(:question).permit(:content, :note_id, :grade_id, :category_id, :chapter_id)
  end

  def find_parent
    if params[:note_id].present?
      @note = Note.find(params[:note_id])
    elsif params[:id].present?
      @question = Question.find(params[:id])
    end
  end
end

app/views/questions/_form.html.haml
= simple_form_for @question, html: { multipart: true, role: 'check-modified' } do |f|
  = f.input :content, as: :summernote, label: false, placeholder: "Your Question...", required: true
  = f.input :grade_id, collection: Grade.order(:name), label_method: :name, value_method: :id, include_blank: false
  = f.input :category_id, collection: Grade.order(:name), as: :grouped_select, group_method: :categories, group_label_method: :id, include_blank: false
  = f.input :chapter_id, collection: Category.order(:name), as: :grouped_select, group_method: :chapters, group_label_method: :id, include_blank: false
  -# = f.input :tag_list, :label=>"Tags (seperated by commas)", placeholder: "Eg. class 12, physics, modern physics, radioactivity, what is radio carbon dating, ...", :input_html=>{:value => @question.tag_list.join(", ")}
  = f.button :submit, class: "btn-sm btn-action"

app/views/questions/_inlineform.html.haml
= simple_form_for([@note, @note.questions.build], html: {id: :inline_new_question, role: 'check-modified'}) do |f|
  %i.far.fa-comment
  = f.input :content, label: false, placeholder: "Write a question...", required: true
  = f.button :submit, value: "Ask question", class: "btn-submit-question btn-sm"

app/views/questions/_inlinequestion.html.haml
.qa-thread.mt-3.mb-4{:id => "qa-thread-#{question.id}"}
  .question.mt-4.mb-2
    .q-header
      .avatar.d-inline
        = image_tag question.user.avatar_address(:small)
      .body.d-inline.ml-1
        = link_to question.user.name, question.user, class: 'username'
        %span.at
          = 'asked'
          = time_ago_in_words(question.created_at)
          ago
      - if can? :destroy, question
        = link_to note_question_path(@note, question), method: :delete, data: { confirm: "Are you sure? Deleting question thread is irreversible." }, remote: true, class: 'btn-delete pull-right' do
          %i.fas.fa-trash
          %span.sr-only= 'Delete thread'
    .q-content
      = simple_format question.content

  - if question.answers.any?
    .answer.mt-4.mb-2{:id =>"answer_#{question.top_ans.id}"}
      .a-header
        .avatar.d-inline
          = image_tag question.answers.first.user.avatar_address(:small)
        .body.d-inline.ml-1
          = link_to question.answers.first.user.name, question.answers.first.user, class: 'username'
          %span.at
            = 'answered'
            = time_ago_in_words(question.answers.first.created_at)
            ago
        - if can? :destroy, question.answers.first
          = link_to note_question_answer_path(@note, question, question.answers.first), method: :delete, data: { confirm: "Are you sure? Deleting your answer is irreversible." }, remote: true, class: 'btn-delete pull-right' do
            %i.fas.fa-trash
            %span.sr-only= 'Delete Answer'
      .a-content
        = simple_format question.top_ans.content
  .question-card-actions.btn-group
    - if user_signed_in?
      %a.q-upvote.q-card-action{:id => "#{question.id}@#!"}= "Helpful (#{question.get_upvotes.size})"
    = link_to 'Read this thread', question_path(question), class: 'q-card-action'

app/views/questions/_note.html.haml
.col-sm-12
  .note
    .note_content.col-lg-8.col-md-12
      %p.info.mb-0
        = note.user.name
        = '•'
        = pluralize(note.view, "Read")
      = link_to note do
        %h3.title.my-1= note.title
        %p.body.mb-1
          = truncate sanitize(note.body, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 330 #truncate(strip_tags(note.body), length: 170)
    .note_image.col-lg-4.col-md-12.d-none.d-lg-block
      = link_to (image_tag note.image.url(:small)), note, class: 'img-note'

app/views/questions/_question.html.haml
%li.col-sm-12
  .question
    .title.wysiwyg
      = link_to question do
        = simple_format(question.content, {}, :sanitize => false)
    .answer.wysiwyg
      - if question.top_ans.present?
        = simple_format(question.top_ans.content, {}, :sanitize => false)

app/views/questions/create.js.haml
:plain
  $('.qa-threads').prepend('#{ j render partial: "inlinequestion", locals: {question: @question} }');
  $('#question_content').val('');

app/views/questions/destroy.js.haml
:plain
  $('#qa-thread-#{@question.id}').fadeOut(300);

app/views/questions/edit.html.haml
#question-edit
  .container
    .qn-internal
      .thread-article
        .thread-form
          .form-card-content
            .form-card-header
              %h2.form-title.mb-0= "Update Your Question Here."
            .form-card-body
              = render 'form'

app/views/questions/index.html.haml
-# #question-index
#note-index
  .ni-body
    .container
      .row
        .menu-col.col-md-4.col-lg-3.offset-lg-1
          .menu.chapters-menu
            %input.search-chapters{:placeholder => "Search chapters..", :type => "text"}
            .chapters-wrap
              %ul.chapters
                - Category.joins(:grade).where(grades: { name: @grade }, name: @category).first.chapters.each do |chapter|
                  %li= link_to chapter.name, notes_url(:grade=>"#{@grade}", :category=>"#{@category}", :chapter=>"#{chapter.id}"), class: "#{'active' if chapter.id == @chapter.to_i}"
            %a.close-chapter-menu.d-block.d-md-none
              %i.fas.fa-times
              Close Menu
        .notes-questions-col.col-md-8.col-lg-7
          .ni-note-info
            %nav{"aria-label" => "breadcrumb"}
              %ol.breadcrumb
                %li.breadcrumb-item.active{"aria-current" => "page"}= "Class #{@grade.humanize} #{@category.humanize}"
                %li.breadcrumb-item.active{"aria-current" => "page"}
                  %h1= Chapter.find(@chapter).name
          %ul.ni-note-tab
            %li.tab-link
              %a#notes
                %span.badge= @notes.count
                Chapter Notes
            %li.tab-link
              %a#questions.active
                %span.badge= @questions.count
                Exercise Questions
          .tabcontent#notes.row.flex-grid
            .index-ad
              %script{:async => "", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
              / Notes inPage
              %ins.adsbygoogle{"data-ad-client" => "ca-pub-8740559156368061", "data-ad-format" => "horizontal", "data-ad-slot" => "8293088026", "data-full-width-responsive" => "true", :style => "display:block"}
              :javascript
                (adsbygoogle = window.adsbygoogle || []).push({});
            - if @notes.present?
              = render @notes
            - else
              %p.mt-5.no-notes-message
                %i.fas.fa-info-circle
                There are no notes in Mattrab Library for this chapter yet.
                %br
                - if can? :create, Note
                  = link_to 'Create Note', new_note_path, class: "btn btn-sm btn-std px-5 mt-4"
                - else
                  = link_to 'Ask a question', new_question_path, class: "btn btn-sm btn-std px-5 mt-4"
          .tabcontent#questions.active.row.flex-grid
            .index-ad
              %script{:async => "", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
              / Questions inPage
              %ins.adsbygoogle{"data-ad-client" => "ca-pub-8740559156368061", "data-ad-format" => "horizontal", "data-ad-slot" => "9850137305", "data-full-width-responsive" => "true", :style => "display:block"}
              :javascript
                (adsbygoogle = window.adsbygoogle || []).push({});
            - if @questions.present?
              %ol.questions
                = render @questions
            - else
              %p.mt-5.no-notes-message
                %i.fas.fa-info-circle
                There are questions in Mattrab Library for this chapter yet.
                %br
                = link_to 'Ask a question', new_question_path, class: "btn btn-sm btn-std px-5 mt-4"

          -# .row.pagination-nav.is.justify-content-center
            = will_paginate @notes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center), previous_label: '&laquo;', next_label: '&raquo;', inner_window: 1, outer_window: 0

app/views/questions/index.js.haml
:plain
  $('#questions.flex-grid').append('#{ j render @questions }');
  $('.pagination-nav').html('#{ j will_paginate @questions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center), previous_label: '&laquo;', next_label: '&raquo;', inner_window: 1, outer_window: 0 }');

app/views/questions/new.html.haml
#question-new
  .container
    .qn-internal
      .returning-option
        = link_to questions_path, class: 'returning-option-link' do
          %i.fas.fa-arrow-left
          = 'Back to Library'
      .info.alert.alert-info.mt-4
        %i.fas.fa-info.mr-2
        Did you search answers for the question you are asking? Make sure you ask question not asked or answered initially.
      .thread-article
        .thread-form
          .form-card-content
            .form-card-header
              %h2.form-title.mb-0= "Ask Your Question Here."
            .form-card-body
              = render 'form'

app/views/questions/show.html.haml

#question-show
  .container
    .qs-internal
      .ad.mb-4
        %script{:async => "", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
        / Questions inPage
        %ins.adsbygoogle{"data-ad-client" => "ca-pub-8740559156368061", "data-ad-format" => "horizontal", "data-ad-slot" => "9850137305", "data-full-width-responsive" => "true", :style => "display:block"}
        :javascript
          (adsbygoogle = window.adsbygoogle || []).push({});
      .thread-article
        .info-action
          .actions
            %nav.nav
              = link_to (@question.note.present? ? note_path(@question.note) : questions_url(:grade => @question.grade.name, :category => @question.category.name, :chapter => @question.chapter.id)), class: "nav-link question-back-action" do
                %i.fas.fa-angle-left
                Back
              - if can? :update, @question
                = link_to "Edit", edit_question_path(@question), class: "nav-link questionquestion-edit-action"
                = link_to "Delete", question_path(@question), method: :delete, data: { confirm: "Are you sure? Deleting your question is irreversible." }, class: "nav-link question-delete-action"
        .thread-question
          .question-card-content
            .question-card-header
              .q-user-avater
                = link_to (image_tag @question.user.avatar_address(:medium)), @question.user
              .q-user-info
                = link_to @question.user do
                  %span.name= @question.user.name
                  %span.asked= "asked in #{@question.note.present? ? @question.note.title : @question.chapter.name}"
            - if @question.note.present?
              .question-card-note
                .note.mb-1
                  %h3.title= truncate @question.note.title, length: 40
                  %p.body.mb-0
                    = truncate sanitize(@question.note.body, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 290
            .question-card-body
              = simple_format(@question.content, {}, :sanitize => false)
            .question-card-actions.btn-group
              - if user_signed_in?
                %a.q-upvote.q-card-action{:id => "#{@question.id}@#!"}= "Helpful (#{@question.get_upvotes.size})"
                %a.toggle-answer-modal.q-card-action= 'Answer this thread'
              - else
                %a.trigger-sign-in.q-card-action{"data-toggle" => "modal", :href => "#sign-in"} Sign in to Answer this Thread
              %a.q-card-info.muted
                %i.fa.fa-reply
                = pluralize(@question.answers.count, "Answer")
              %a.q-card-info.muted
                %i.fa.fa-eye
                = pluralize(@question.view, "View")
        .thread-answers
          - @answers.each do |answer|
            = render 'answers/answer', question: @question, answer: answer

          -# rendering modal form.
          - if user_signed_in?
            .submit-answer-modal.overlay.d-none
              .sa-modal-body.mr-animate-bitzoom
                .sa-model-content
                  .sa-model-header
                    %h3.sa-modal-title.mb-0= "Your answer to '#{truncate sanitize(@question.content, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 50}'"
                  .answer-form.form{:id => "question-#{@question.id}-answer-form"}
                    .body
                      - if can? :create, Answer
                        = render "answers/cform", :question => @question
                      - else
                        %p= 'You cannot create answers.'

            .edit-answer-modal.overlay.d-none
              .ea-modal-body.mr-animate-bitzoom
                .ea-model-content
                  .ea-model-header
                    %h3.ea-modal-title.mb-0= "Edit your answer to '#{truncate sanitize(@question.content, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 50}'"
                  .answer-form.form{:id => "question-#{@question.id}-answer-form"}
                    .edit-form-body
                      -# edit form will be rendered here.