config/routes.rb
Rails.application.routes.draw do

  get '/sitemap', to: redirect("https://#{ENV.fetch('S3_BUCKET_NAME')}.s3.amazonaws.com/sitemaps/sitemap.xml.gz")

  %w[about faqs affiliate_program terms privacy creator_appeal admin_action apply].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users' }
  get 'users/show'
  resources :users do
    resources :categorizations
    member do
      get :following, :followers
      get "change_role",  to: "users#change_role"
    end
  end
  resources :relationships
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'searches#search'
  get 'home', to: 'notes#home'
  resources :notes do
    collection do
      post :import
    end
    member do
      put "thank", to: "notes#vote"
      get "suggest", to: "notes#suggest"
      get "verify", to: "notes#verify"
      get "request_verification",  to: "notes#request_verification"
    end
    resources :questions, only: [:create, :destroy] do
      resources :answers, only: [:create, :destroy]
    end
  end
  resources :questions do
    member do
      put "vote", to: "questions#vote"
    end
    resources :answers, only: [:create, :edit, :update, :destroy] do
      put "vote", to: "answers#vote"
    end
  end
  resources :images, only: [:create, :destroy]
  root 'notes#home'
end

app/models/note.rb
class Note < ApplicationRecord
  before_update :unpublish_if_unverified
  after_update :create_notifications

  validates :title, presence: true
  validates :body, presence: true

  enum grade: [:twelve, :eleven]
  enum category: [:physics, :chemistry, :biology, :maths, :computer, :english, :nepali, :pastpapers, :solution]
  enum status: [:draft, :published]

  acts_as_votable

  belongs_to :user
  belongs_to :grade
  belongs_to :category
  belongs_to :chapter
  has_many :questions, dependent: :delete_all

  has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }, default_url: "/images/small/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  include PgSearch
  pg_search_scope :search, against: [:title, :body],
    using: {tsearch: {dictionary: 'english'}},
    associated_against: {user: :name, grade: :name, category: :name, chapter: :name, questions: :content}

  def to_param
    "#{id} #{title}".parameterize
  end

  def unpublish_if_unverified
    if self.is_verified_changed? and self.is_verified == false and self.published?
      self.status = "draft"
    end
  end

  def request_verification(admin)
    if self.is_verified == false
      Notification.create(recipient: admin, actor: self.user, action: 'asked for Verification of', notifiable: self)
    end
  end

  def suggest(feedback, user)
    self.update_attribute(:feedback, feedback)
    Notification.create(recipient: self.user, actor: user, action: 'has suggestions for', notifiable: self)
  end

  def create_notifications
    if self.status_changed? and self.is_verified == true and self.published?
      self.user.followers.each do |recipient|
        Notification.create(recipient: recipient, actor: self.user, action: 'updated', notifiable: self)
      end
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:home, :index, :show, :search]
  before_action :find_note, only: [:show, :edit, :update, :destroy, :vote, :verify]

  def home
    # global feeds
    if user_signed_in?
      general_feeds = Question.where.not(user_id: current_user).order("created_at DESC, view DESC").limit(18).to_a
      @feeds = general_feeds.concat(current_user.feeds).uniq.shuffle.paginate(page: params[:page], per_page: 7)
      @voted_notes = current_user.voted_notes.shuffle
    else
      general_feeds = Question.all.order("created_at DESC, view DESC").limit(49).to_a
      @feeds = general_feeds.shuffle.paginate(page: params[:page], per_page: 7)
      @voted_notes = Note.published.order("created_at DESC, view DESC").limit(11).shuffle
    end
    @top_creators = User.where(:role => "creator").joins(:notes).where("notes.status = ?", 1).group("users.id").order("count(users.id) DESC").limit(3)
    @top_learners = User.where(:role => "learner").joins(:questions).group("users.id").order("count(users.id) DESC").limit(3)
    @recent_users = User.all.order("created_at DESC").limit(2)
    @icons = {'physics'=>'satellite', 'chemistry'=>'flask', 'biology'=>'microscope', 'maths'=>'subscript', 'computer'=>'plug', 'english'=>'sort-alpha-up-alt', 'nepali'=>'torah', 'economics'=>'chart-line', 'account'=>'funnel-dollar', 'science'=>'magnet', 'social'=>'globe-asia', 'health'=>'walking', 'moral'=>'balance-scale', 'obt'=>'chart-bar', 'opt_math'=>'square-root-alt', 'pastpapers'=>'paste', 'solution'=>'pencil-ruler', 'trivia'=>'bullhorn', 'philosopy'=>'hourglass-start'}
  end

  def index
    params[:grade].present? ? @grade = params[:grade] : @grade = 'twelve'
    if params[:category].present?
      @category = params[:category]
      category_id = Category.joins(:grade).where(grades: { name: @grade }, name: params[:category]).first.id
    else
      @category = Category.joins(:grade).where(grades: { name: @grade }).first.name
      category_id = Category.joins(:grade).where(grades: { name: @grade }).first.id
    end
    params[:chapter].present? ? @chapter = params[:chapter] : @chapter = Chapter.joins(:category).where(categories: {id: category_id}).first.id

    @notes = Note.joins(:grade).where(grades: { name: @grade }).
                  joins(:category).where(categories: { id: category_id }).
                  joins(:chapter).where(chapters: { id: @chapter }).
                  published.order("created_at ASC")
    @questions = Question.joins(:grade).where(grades: { name: @grade }).
                  joins(:category).where(categories: { id: category_id }).
                  joins(:chapter).where(chapters: { id: @chapter }).
                  order("created_at ASC")

    set_meta_tags title: "Class #{@grade.humanize} #{@category.humanize}", site: 'Mattrab', description: "Browse high-quality notes, questions, and answers for #{Chapter.find(@chapter).name} of class #{@grade} #{@category} subject.", keywords: "Class #{@grade}, #{@category}, #{Chapter.find(@chapter).name}, notes for class #{@grade} #{@category}, notes for #{Chapter.find(@chapter).name}, question answer for class #{@grade} #{@category}",
                  og: { title: "Class #{@grade.humanize} #{@category.humanize}: #{Chapter.find(@chapter).name}", description: "Browse high-quality notes, questions, and answers for #{Chapter.find(@chapter).name} of class #{@grade} #{@category} subject.", type: 'website', url: notes_url(:grade=>"#{@grade}", :category=>"#{@category}", :chapter=>@chapter)},
                  twitter: { title: "Class #{@grade.humanize} #{@category.humanize}: #{Chapter.find(@chapter).name}", description: "Browse high-quality notes, questions, and answers for #{Chapter.find(@chapter).name} of class #{@grade} #{@category} subject." }
  end

  def show
    @questions = Question.where(note_id: @note).order("created_at DESC")
    @random_note = Note.joins(:chapter).where(chapters: { id: @note.chapter.id }).where("notes.id > ?", @note.id).
                        published.where.not(id: @note).order("id ASC").first
    @random_note = Note.joins(:category).where(categories: { id: @note.category.id }).
                        published.where.not(id: @note).order("RANDOM()").first if !@random_note.present?
    @random_note = Note.published.where.not(id: @note).order("RANDOM()").first if !@random_note.present?
    @note.update_attribute "view", @note.view += 1
    set_meta_tags title: @note.title, site: "Class #{@note.grade.name.humanize} #{@note.category.name.humanize}", description: @note.body.gsub(/<[^>]*>/, '').truncate(350), keywords: "#{@note.chapter.name}, note on #{@note.chapter.name}, class #{@note.grade.name} #{@note.category.name} note, class #{@note.grade.name} notes, #{@note.chapter.name} notes", author: @note.user.name, next: note_url(@random_note),
                  og: { title: @note.title, description: @note.body.gsub(/<[^>]*>/, '').truncate(350), type: 'website', url: note_url(@note), image: @note.image },
                  twitter: { title: @note.title, description: @note.body.gsub(/<[^>]*>/, '').truncate(350), image: @note.image }
  end

  def new
    @note = current_user.notes.build
  end

  def create
    params[:note][:body] = params[:note][:body].gsub('source', '<span>source</span>').gsub('position: fixed', '<span>position: fixed</span>').gsub('position:fixed', '<span>position:fixed</span>').gsub('method="delete"', '').gsub('link', '<span>link</span>').gsub('script', '<span>script</span>').gsub("method='delete'", '').gsub(/<iframe .*src="(https?:\/\/)?(?!(?:\/\/www.youtube.com\/embed\/|\/\/player.vimeo.com\/video\/)).*><\/iframe>/, '')
                                .gsub('onerror', '<span>onerror</span>').gsub('onclick', '<span>onclick</span>').gsub('onload', '<span>onload</span>').gsub('onchange', '<span>onchange</span>').gsub('onmouseover', '<span>onmouseover</span>').gsub('onmouseout', '<span>onmouseout</span>').gsub('onmousedown', '<span>onmousedown</span>').gsub('onmouseup', '<span>onmouseup</span>').gsub('onfocus', '<span>onfocus</span>').gsub(/[\r\n]+/, ' ').html_safe
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to edit_note_url(@note)
    else
      render 'new'
    end
  end

  def edit
    @admins = User.admin.where(:category_id => @note.category.id)
    @admins = User.admin if !@admins.present?
    set_meta_tags title: 'Edit '+@note.title, site: 'Mattrab'
  end

  def update
    params[:note][:body] = params[:note][:body].gsub('source', '<span>source</span>').gsub('position: fixed', '<span>position: fixed</span>').gsub('position:fixed', '<span>position:fixed</span>').gsub('method="delete"', '').gsub('link', '<span>link</span>').gsub('script', '<span>script</span>').gsub("method='delete'", '').gsub(/<iframe .*src="(https?:\/\/)?(?!(?:\/\/www.youtube.com\/embed\/|\/\/player.vimeo.com\/video\/)).*><\/iframe>/, '')
                                .gsub('onerror', '<span>onerror</span>').gsub('onclick', '<span>onclick</span>').gsub('onload', '<span>onload</span>').gsub('onchange', '<span>onchange</span>').gsub('onmouseover', '<span>onmouseover</span>').gsub('onmouseout', '<span>onmouseout</span>').gsub('onmousedown', '<span>onmousedown</span>').gsub('onmouseup', '<span>onmouseup</span>').gsub('onfocus', '<span>onfocus</span>').gsub(/[\r\n]+/, ' ').html_safe
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path, notice: 'Note deleted successfully.'
  end

  def vote
    if !current_user.liked? @note
      @note.liked_by current_user
    else
      @note.unliked_by current_user
    end
    render :json => { :count => @note.get_upvotes.size }
  end

  def request_verification
    @note.request_verification(User.find(params[:admin]))
    redirect_back fallback_location: @note
  end

  def suggest
    @note.suggest(params[:feedback], current_user)
    redirect_back fallback_location: @note
  end

  def verify
    @note.update_attribute(:is_verified, params[:is_verified])
    @note.update_attribute(:feedback, nil)
    redirect_back fallback_location: @note
  end

  def import
    Chapter.import(params[:file])
    redirect_to root_url, notice: "Categories Imported."
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body, :image, :category, :status, :grade, :grade_id, :category_id, :chapter_id, :feedback)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/home.html.haml

.banner
  .banner-content
    %nav.grade-nav
      %ul.grade-list
        - if user_signed_in?
          - Grade.all.each do |grade|
            %li.grade-item{class: "#{grade == current_user.grade ? 'active' : ' '}"}
              = link_to grade.name.humanize, "#", class: "grade-link", id: grade.name
        - else
          - Grade.all.each do |grade|
            %li.grade-item{class: "#{grade == Grade.all.first ? 'active' : ' '}"}
              = link_to grade.name.humanize, "#", class: "grade-link", id: grade.name

.sticky-subnav
  .subnav-row
    .twelve.columns
      - if user_signed_in?
        - Grade.all.each do |grade|
          %ul.sticky-subnav-list.category-list.category-list{:id=>grade.name, class: "#{grade == current_user.grade ? 'active' : ' '}"}
            - grade.categories.each do |category|
              %li.cat-item.category-item
                = link_to notes_url(:grade=>"#{grade.name}", :category=>"#{category.name}", :chapter=>"#{category.chapters.first.try(:id)}") do
                  %i.fa{class: "fa-#{@icons[category.name]}"}
                  = category.name.humanize
      - else
        - Grade.all.each do |grade|
          %ul.sticky-subnav-list.category-list.category-list{:id=>grade.name, class: "#{grade == Grade.all.first ? 'active' : ' '}"}
            - grade.categories.each do |category|
              %li.cat-item.category-item
                = link_to notes_url(:grade=>"#{grade.name}", :category=>"#{category.name}", :chapter=>"#{category.chapters.first.try(:id)}") do
                  %i.fa{class: "fa-#{@icons[category.name]}"}
                  = category.name.humanize

#feed-assets
  .container
    .row.fa-row
      .col-12.col-sm-12.col-md-3.col-lg-3.d-none.d-lg-block.menu-col
        .mattrabians.sticky-in-desktop
          .users-around
            -# %h3.mb-3
            -#   %i.fas.fa-users
            -#   Mattrabians around you
            - @top_creators.each do |top_creator|
              .mattrabian-info
                .user-avater
                  = link_to (image_tag top_creator.avatar_address(:medium)), top_creator
                .user-info
                  = link_to top_creator do
                    %span.name= top_creator.name
                  %span.info= 'Top Creator'
                .options
                  - if user_signed_in?
                    - if current_user != top_creator
                      - if !current_user.following?(top_creator)
                        = form_for(current_user.active_relationships.build) do |f|
                          = hidden_field_tag :followed_id, top_creator.id
                          = f.submit "Follow", class: "follow"
                      - else
                        = form_for(current_user.active_relationships.find_by(followed_id: top_creator.id), html: { method: :delete }) do |f|
                          = f.submit "Unfollow", class: "follow"
                    - else
                      = link_to "Settings", edit_user_registration_path, class: 'follow'
                  - else
                    %a.trigger-sign-in.follow{"data-toggle" => "modal", :href => "#sign-in"} Follow
            - @top_learners.each do |top_learner|
              .mattrabian-info
                .user-avater
                  = link_to (image_tag top_learner.avatar_address(:medium)), top_learner
                .user-info
                  = link_to top_learner do
                    %span.name= top_learner.name
                  %span.info= 'Top Learner'
                .options
                  - if user_signed_in?
                    - if current_user != top_learner
                      - if !current_user.following?(top_learner)
                        = form_for(current_user.active_relationships.build) do |f|
                          = hidden_field_tag :followed_id, top_learner.id
                          = f.submit "Follow", class: "follow"
                      - else
                        = form_for(current_user.active_relationships.find_by(followed_id: top_learner.id), html: { method: :delete }) do |f|
                          = f.submit "Unfollow", class: "follow"
                    - else
                      = link_to "Settings", edit_user_registration_path, class: 'follow'
                  - else
                    %a.trigger-sign-in.follow{"data-toggle" => "modal", :href => "#sign-in"} Follow
            - @recent_users.each do |recent_user|
              .mattrabian-info
                .user-avater
                  = link_to (image_tag recent_user.avatar_address(:medium)), recent_user
                .user-info
                  = link_to recent_user do
                    %span.name= recent_user.name
                  %span.info= 'Recently joined'
                .options
                  - if user_signed_in?
                    - if current_user != recent_user
                      - if !current_user.following?(recent_user)
                        = form_for(current_user.active_relationships.build) do |f|
                          = hidden_field_tag :followed_id, recent_user.id
                          = f.submit "Follow", class: "follow"
                      - else
                        = form_for(current_user.active_relationships.find_by(followed_id: recent_user.id), html: { method: :delete }) do |f|
                          = f.submit "Unfollow", class: "follow"
                    - else
                      = link_to "Settings", edit_user_registration_path, class: 'follow'
                  - else
                    %a.trigger-sign-in.follow{"data-toggle" => "modal", :href => "#sign-in"} Follow

      .col-12.col-sm-12.col-md-8.col-lg-6.feed-col
        .mattrab-feed
          .intro-item
            .intro-item-content
              .intro-item-header
                .i-user-avater
                  = image_tag 'mricon.png'
                .i-user-info
                  %span.name Mattrab Community
                  %span.about Largest students' community in Nepal.
              .intro-item-body
                .welcome
                  = "Namaste! #{!user_signed_in? ? 'Log in to ask your questions and follow your friends.' : (user_signed_in? and current_user.about.present?) ? 'Look aroud what your friends are doing at Mattrab.' : 'Update your setting to experience the best.'}"
                  -# Welcome! We are accepting application from all over Nepal.
                  -# = link_to apply_path, class: 'immediate-action' do
                  -#   %i.far.fa-edit
                  -#   Apply to Mattrab Community
          .collab-item
            .intro-item-content
              .intro-item-header
                .i-user-avater
                  = image_tag 'eu-5-logo.png'
                .i-user-info
                  %span.name EU 5 Series
                  %span.about EU 5 is celebrating May as Mental Health Month.
              .collab-item-body
                .welcome
                  May as a mental health awareness month was first observed in USA in 1949.
                  The purpose is to raise awareness among the larger public and the policymakers about mental health issues, the stigma surrounding it and a reminder to individuals to take care of their mental health.
                  Mattrab Community and EU 5 series, we are celebrating this month by sharing a letter each day.
                  = link_to notes_url(:grade=>'twelve',:category=>'trivia',:chapter=>787), class: 'immediate-action' do
                    %i.fas.fa-palette
                    Read the Letters

          -# - if @voted_notes.present?
          -#   .voted-notes
          -#     - @voted_notes.each do |note|
          -#       .upvoted-note
          -#         .feed-item-header
          -#           .f-upvoted-avater
          -#             %span
          -#               %i.fas.fa-heart
          -#           .f-upvoted-info
          -#             = link_to current_user do
          -#               %span.name= "#{user_signed_in? ? 'Your Favorite Readings' : 'Top Readings'}"
          -#             %span.asked= "#{user_signed_in? ? 'You thanked for these notes.' : 'These notes are most read.'}"
          -#         .feed-item-body
          -#           .note.mb-1
          -#             .note_image.col-lg-5.col-md-12
          -#               = image_tag note.image.url(:small), class: 'img-note'
          -#             .note_content.col-lg-7.col-md-12
          -#               %h3.title.mb-1= truncate note.title, length: 31
          -#               %p.body.mb-1
          -#                 = truncate sanitize(note.body, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 180
          -#         .feed-item-actions.btn-group
          -#           %a.prev-note.u-note-action ❮
          -#           = link_to note_path(note), class: 'u-note-action' do
          -#             %i.far.fa-eye
          -#             Read this Note
          -#           %a.next-note.u-note-action ❯
          -#           %p.u-note-info
          -#             = "Read #{note.view} times"

          -# .feed-ad
          -#   .feed-ad-header
          -#     .f-sponsor-avater
          -#       = image_tag 'google.png'
          -#     .f-sponsor-info
          -#       %span.name Google Adsense
          -#       %span.message We thank Google for helping us through our journey.
          -#   %script{:async => "", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
          -#   %ins.adsbygoogle{"data-ad-client" => "ca-pub-8740559156368061", "data-ad-format" => "fluid", "data-ad-layout-key" => "-fc-p-2q-dn+191", "data-ad-slot" => "7280578627", :style => "display:block"}
          -#   :javascript
          -#     (adsbygoogle = window.adsbygoogle || []).push({});
          = render :partial => "feed", :collection => @feeds if @feeds.present?
        .pagination-nav.is.justify-content-center
          = will_paginate @feeds, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center), previous_label: '&laquo;', next_label: '&raquo;', inner_window: 1, outer_window: 0

      .col-12.col-sm-12.col-md-4.col-lg-3.assets-col
        .home-sidebar.sticky-in-desktop
          - if user_signed_in?
            .current-user-info
              .c-user-avater
                = link_to (image_tag current_user.avatar_address(:medium)), current_user
              .c-user-info
                = link_to current_user do
                  %span.name= current_user.name
                %span.info
                  = current_user.role.humanize
                  = '•'
                  = link_to 'Settings', edit_user_registration_path
          .encourage
            - if !user_signed_in?
              %h2.en-title Mattrab Community
              %p.en-message.mx-auto Create, share and learn from the unlimited notes, photos and videos and ask your questions, answer your friends all over Nepal and grow. Create, share and learn.
              .actions
                %a.trigger-sign-in.action-button.mx-auto.mb-2{"data-toggle" => "modal", :href => "#sign-in"} Join Community, it's free!
                %a.trigger-about-video.action-button.mx-auto{"data-toggle" => "modal", :href => "#about-video"} Watch about Mattrab
            - elsif can? :create, Note
              %h2.en-title Showcase your Knowledge
              %p.en-message.mx-auto Yay! You are creator in Mattrab Community. Share what you have learned around your friends, help them learn like you do and get recognized around the Community.
              .actions
                = link_to new_question_path, class: 'action-button mx-auto mb-2' do
                  %i.far.fa-comment-alt
                  Ask new Question
                = link_to new_note_path, class: 'action-button mx-auto' do
                  %i.far.fa-edit
                  Create Note
            - else
              %h2.en-title Add to your Knowledge
              %p.en-message.mx-auto Not understanding any topic or subjects? Ask your question and get helps form friends around the Community. Answers to your questions can help several later.
              .actions
                = link_to new_question_path, class: 'action-button mx-auto mb-3' do
                  %i.far.fa-comment-alt
                  Ask new Question
                = link_to creator_appeal_path, class: 'action-button mx-auto' do
                  %i.far.fa-edit
                  Be a Creator

#about-video.about-video-modal
  .video-content
    %a.close-about-video{"data-toggle" => "modal", :href => "#about-video"}
      %i.fas.fa-times
    %iframe.raLsWLhsVZ.about-video{:allow => "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :src => "https://www.youtube.com/embed/bVckO9Psd1E"}

app/views/notes/new.html.haml

#note-edition.pt-5
  .edition-head-nav.container
    .info.alert.alert-info
      %i.fas.fa-info.mr-2
      Did you search the topic you are writing about? Make sure you write on topic not covered initially.
    .d-flex.flex-row-reverse.py-2
      -# - if can? :destroy, @note
      -#   = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "note-action ml-3 delete"
      -# - if can? :verify, @note
      -#   = link_to @note.is_verified? ? "Unverify" : "Verify", verify_note_path(@note, :is_verified => !@note.is_verified), method: :get, class: "note-action ml-3"
  = render 'form'

app/views/notes/show.html.haml

#note-show
  .container
    .row.py-5
      .this-note.col-md-9
        .page
          .unit-head
            .info-action
              .actions
                %nav.nav
                  = link_to notes_url(:grade => @note.grade.name, :category => @note.category.name, :chapter => @note.chapter.id), class: "nav-link note-back-action" do
                    %i.fas.fa-angle-left
                    Back
                  - if can? :update, @note
                    = link_to "Edit", edit_note_path(@note), class: "nav-link note-edit-action"
                    = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure? Deleting your note is irreversible." }, class: "nav-link note-delete-action"
            .headline
              .col-md-8.heading
                %h1.unit-name.mb-0.mt-1= @note.title
              .col-md-4.image
                = image_tag @note.image.url(:small)
          .head-nav
            .col-md-12
              %nav.nav.justify-content-center
                - if user_signed_in?
                  %button.n-upvote.nav-link.first{:id => "#{@note.id}@#!"}
                    %i.fa.fa-heart
                    %span.thanks-count= pluralize(@note.get_upvotes.size, "Thank")
                - else
                  %a.trigger-sign-in.nav-link.first.mb-0{"data-toggle" => "modal", :href => "#sign-in"}
                    %i.fa.fa-heart
                    %span.thanks-count= pluralize(@note.get_upvotes.size, "Thank")
                %p.nav-link.mb-0
                  %i.fa.fa-comments
                  = pluralize(@note.questions.count, "Question")
                %p.nav-link.mb-0
                  %i.fa.fa-eye
                  = pluralize(@note.view, "View")
                %button.print-note.nav-link
                  %i.fa.fa-print
                  Print Note
                %p.nav-link.mb-0
                  %i.fa.fa-share-alt
                  by
                  = link_to @note.user.name, @note.user
                  = time_ago_in_words(@note.created_at)
                  ago

          .unit-body
            = simple_format(@note.body, {}, :sanitize => false)
            .ad
              -# = image_tag 'adhere.png'
              %script{:async => "", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
              / Notes inPage
              %ins.adsbygoogle{"data-ad-client" => "ca-pub-8740559156368061", "data-ad-format" => "horizontal", "data-ad-slot" => "8293088026", "data-full-width-responsive" => "true", :style => "display:block"}
              :javascript
                (adsbygoogle = window.adsbygoogle || []).push({});
            .tags
              = link_to search_url(:query => @note.grade.name), class: "tag" do
                %i.fa.fa-hashtag
                = @note.grade.name
              = link_to search_url(:query => @note.category.name), class: "tag" do
                %i.fa.fa-hashtag
                = @note.category.name
              = link_to search_url(:query => @note.chapter.name), class: "tag" do
                %i.fa.fa-hashtag
                = @note.chapter.name

            %p.paper-message
              %span.brand-print
                %span.ask ask
                mattrab
              Visit www.askmattrab.com for more academic resources.

        .page-discussions.mb-5
          %h2.title.mb-3 Discussions
          .ask
            .question-form.form
              - if user_signed_in?
                - if can? :create, Question
                  = render "questions/inlineform"
                - else
                  %p= 'You cannot create questions.'
              - else
                %p.login-msg
                  = 'Please '
                  %a.trigger-sign-in{"data-toggle" => "modal", :href => "#sign-in"} Log In
                  = 'to ask your question.'
          .qa-threads
            - @questions.each do |question|
              = render 'questions/inlinequestion', question: question

      .random-notes.col-md-3
        .rn-wrap.mb-5
          .random-note
            .note_content
              %p.info.mb-2= "Next topic by #{@random_note.user.name}"
              %h2.title= link_to @random_note.title, @random_note
              %p.body
                = truncate sanitize(@random_note.body, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 150
              %p.buttons
                %span
                  %i.fa.fa-comments-o
                  = pluralize(@random_note.questions.count, "Question")
                %span
                  %i.fa.fa-thumbs-o-up
                  = pluralize(@random_note.get_upvotes.size, "Thank")
                %span
                  %i.fa.fa-eye
                  = pluralize(@random_note.view, "View")

          .ad
            %script{:async => "", :crossorigin => "anonymous", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8740559156368061"}
            / Notes inSide
            %ins.adsbygoogle{"data-ad-client" => "ca-pub-8740559156368061", "data-ad-format" => "rectangle", "data-ad-slot" => "2095301175", "data-full-width-responsive" => "true", :style => "display:block"}
            :javascript
              (adsbygoogle = window.adsbygoogle || []).push({});

          .author.justify-content-center
            .user-main
              .user-avater
                = link_to (image_tag @note.user.avatar_address(:medium)), @note.user
              .user-name
                = link_to @note.user.name, @note.user, class: 'name'
            .user-info
              %p.about.mb-2= truncate @note.user.about, length: 110
              %p.has
                %i.fa.fa-link
                = "Has #{pluralize(@note.user.followers.count, 'Follower')}"