config/routes.rb
Rails.application.routes.draw do

  get '/sitemap', to: redirect("https://#{ENV.fetch('S3_BUCKET_NAME')}.s3.amazonaws.com/sitemaps/sitemap.xml.gz")

  %w[about faqs affiliate_program terms privacy creator_appeal admin_action apply].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users' }
  get 'users/show'
  resources :users do
    resources :categorizations
    member do
      get :following, :followers
      get "change_role",  to: "users#change_role"
    end
  end
  resources :relationships
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'searches#search'
  get 'home', to: 'notes#home'
  resources :notes do
    collection do
      post :import
    end
    member do
      put "thank", to: "notes#vote"
      get "suggest", to: "notes#suggest"
      get "verify", to: "notes#verify"
      get "request_verification",  to: "notes#request_verification"
    end
    resources :questions, only: [:create, :destroy] do
      resources :answers, only: [:create, :destroy]
    end
  end
  resources :questions do
    member do
      put "vote", to: "questions#vote"
    end
    resources :answers, only: [:create, :edit, :update, :destroy] do
      put "vote", to: "answers#vote"
    end
  end
  resources :images, only: [:create, :destroy]
  root 'notes#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:google_oauth2]

  belongs_to :grade
  belongs_to :category
  has_many :notes, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :answered_questions, through: :answers, source: :question

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :notifications, foreign_key: :recipient_id

  acts_as_voter
  enum role: [:learner, :creator, :admin, :executive, :teacher, :superadmin]
  enum admin_category: [:physics, :chemistry, :biology, :maths, :computer, :english, :nepali, :pastpapers, :solution]
  enum egrade: [:twelve, :eleven, :ten]

  include PgSearch
  pg_search_scope :search, against: [:name, :about],
    using: {tsearch: {dictionary: 'english'}},
    associated_against: {notes: :title, questions: :content}

  def to_param
    "#{id} #{name}".parameterize
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    where(email: data['email'], uid: access_token.uid).first_or_create(name: data['name'], email: data['email'], uid: access_token.uid, avatar_url: data['image'], confirmed_at: Time.now)
  end

  def self.new_with_session(params, session)
    if session['devise.google_data']
      new session["devise.google_data"] do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && uid.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def voted_notes
    self.get_up_voted Note.limit(11)
  end

  def feeds
    fquestions = Question.where(user_id: self.followers).where('updated_at > ?', 24.hours.ago).to_a
    nquestions = Question.where(note_id: self.notes).where('updated_at > ?', 24.hours.ago).to_a
    aquestions = Answer.where(question_id: self.questions).where('updated_at > ?', 24.hours.ago).to_a
    return [fquestions, nquestions, aquestions].reduce([], :concat).uniq.shuffle
  end

  ## helper methods
  # follow another user
  def follow(other)
    active_relationships.create(followed_id: other.id)
  end
  # unfollow a user
  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end
  # is following a user?
  def following?(other)
    following.include?(other)
  end

  def avatar_address(size)
    if self.avatar.present?
      self.avatar.url(size)
    elsif self.uid.present?
      self.avatar_url
    else
      '/images/pro/missing.png'
    end
  end

  has_attached_file :avatar, styles: {pro: "250x250#", medium: "70x70>", small: "35x35>" }, default_url: "/images/pro/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #prevents if any other actions are not to be accessible.
  before_action :authenticate_user!, except: [:show, :google_oauth2, :failure]
  before_action :find_user, only: [:show, :change_role]
  def show
    if params[:tab].present?
      @tab = params[:tab]
    elsif @user.creator? or @user.admin? or @user.executive? or @user.teacher? or @user.superadmin?
      @tab = "note"
    else
      @tab = "question"
    end

    case @tab
    when "question"
      @questions = @user.questions.all.paginate(page: params[:page], per_page: 7).order("created_at DESC")
    when "answer"
      @questions = @user.answered_questions.uniq.paginate(page: params[:page], per_page: 7)
    when "about"
      @total_views = @user.notes.sum(:view) #+ @user.questions.sum(:view)
    else
      if @user == current_user or (user_signed_in? and current_user.admin?)
        @notes = @user.notes.all.paginate(page: params[:page], per_page: 7).order("created_at DESC")
      else
        @notes = @user.notes.published.paginate(page: params[:page], per_page: 7).order("created_at DESC")
      end
    end

    if @user.about.present? and @user.avatar.present?
      set_meta_tags title: @user.name, site: 'Mattrab '+@user.role.humanize, description: @user.about.gsub(/<[^>]*>/, '').truncate(150), keywords: "#{@user.name}, Mattrab #{@user.role}, Mattrab user",
                    og: { title: @user.name, description: @user.about.gsub(/<[^>]*>/, '').truncate(150), type: 'website', url: user_url(@user), image: @user.avatar },
                    twitter: { title: @user.name, description: @user.about.gsub(/<[^>]*>/, '').truncate(150), image: @user.avatar }
    else
      set_meta_tags title: @user.name, site: 'Mattrab '+@user.role.humanize, keywords: "#{@user.name}, Mattrab #{@user.role}, Mattrab user",
                    og: { title: @user.name, type: 'website', url: user_url(@user) },
                    twitter: { title: @user.name }
    end
  end

  def change_role
    @user.update_attribute(:role, params[:role].to_i)
    redirect_back fallback_location: @user
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
    else
      session['devise.google_data'] = @user.attributes
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    flash[:error] = "Couldn't sign in. Please try again."
    redirect_to new_user_registration_url
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
#profile
  .this-wrap
    .container
      .col-md-3
        .this-face-wrap.mb-5
          %span.badge-base
            %span.badge.center= @user.role
          .this-face
            .face= image_tag @user.avatar_address(:pro), class: "img-circle center"
            %h2.name.mt-3.mb-2
              = @user.name
              - if @user.notes.count >= 15 or @user.creator? or @user.admin? or @user.superadmin?
                %span
                  %i.fa.fa-check-circle
            %ul.has.mt-0
              %li.has-info
                %i.fa.fa-link
                = "Has #{pluralize(@user.followers.count, "Follower")}"
              - if @user.creator? or @user.admin? or @user.superadmin?
                %li.has-info
                  %i.fa.fa-edit
                  = "Created #{pluralize(@user.notes.published.count, "Note")}"
              %li.has-info
                %i.far.fa-question-circle
                = "Asked #{pluralize(@user.questions.count, "Question")}"
              %li.has-info
                %i.fa.fa-reply
                = "Answered #{pluralize(@user.answered_questions.count, "Question")}"
            .follow.edit
              - if user_signed_in?
                - if current_user != @user
                  - if !current_user.following?(@user)
                    = form_for(current_user.active_relationships.build) do |f|
                      = hidden_field_tag :followed_id, @user.id
                      = f.submit "Follow", class: "btn-std btn-sm btn-follow-edit"
                  - else
                    = form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f|
                      = f.submit "Following", class: "btn-std btn-sm btn-follow-edit"
                - else
                  = link_to "Settings", edit_user_registration_path, class: 'btn-std btn-sm btn-follow-edit'
              - else
                %a.trigger-sign-in.btn-std.btn-sm.btn-follow-edit{"data-toggle" => "modal", :href => "#sign-in"} Follow

      .col-md-9
        .this-property
          .this-property-nav
            .navbar-internal
              .left-links
                - if @user.creator? or @user.admin? or @user.executive? or @user.teacher? or @user.superadmin?
                  = link_to user_path(@user, :tab => :note), class: "qi-navbar-link", id: (@tab=="note" ? 'active' : '') do
                    %i.fas.fa-edit
                    %span.d-none.d-lg-inline= 'Academic/Research'
                    = 'Notes'
                = link_to user_path(@user, :tab => :question), class: "qi-navbar-link active", id: (@tab=="question" ? 'active' : '') do
                  %i.far.fa-question-circle
                  = 'Asked'
                  %span.d-none.d-lg-inline= 'Questions'
                = link_to user_path(@user, :tab => :answer), class: "qi-navbar-link", id: (@tab=="answer" ? 'active' : '') do
                  %i.fas.fa-reply
                  = 'Answered'
                  %span.d-none.d-lg-inline= 'Questions'
                = link_to user_path(@user, :tab => :about), class: "qi-navbar-link", id: (@tab=="about" ? 'active' : '') do
                  %i.fas.fa-info-circle
                  = 'About'

          - if @tab == 'question' or @tab == 'answer'
            .questions.pt-4
              - if @questions.present?
                - @questions.each do |question|
                  .row
                    .col-lg-9.col-md-10.col-sm-12
                      .question.p-3
                        = link_to question do
                          %p.user-info.mb-2
                            = "#{question.chapter.name.humanize} •"
                            = pluralize(question.answers.count, "Answer")
                          %h3.title.mb-2= truncate sanitize(question.content, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 200
                    .col-lg-3.col-md-2.col-sm-12
                      - if can? :update, question
                        = link_to "Edit", edit_question_path(question), class: "btn-sm"
                      - if can? :destroy, question
                        = link_to "Delete", question_path(question), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-sm delete"
                .pagination-nav.pt-4
                  = will_paginate @questions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center), previous_label: '&laquo;', next_label: '&raquo;', inner_window: 1, outer_window: 0
              - else
                %p.no-property No questions asked yet.
          - elsif @tab == 'about'
            .about
              %p.title= 'Hi, welcome to my library.'
              %p.about_text
                - if @user.about == nil and  @user == current_user
                  = link_to "Write more about yourself here.", edit_user_registration_path
                - else
                  = @user.about
              %p.joined.mb-1= "Joined Mattrab Community on #{@user.created_at.strftime("%B %d, %Y")}."
              %p.views= "Total #{@total_views} views."
            - if can? :change_role, @user
              .d-flex.flex-row.py-2
                = select_tag "role", options_for_select(User.roles)
                %button.change-role.ml-3{:id=>"#{@user.id}@#!"}= 'Change Role'
          - else
            - if @user.creator? or @user.admin? or @user.executive? or @user.teacher? or @user.superadmin?
              .notes.pt-4
                - if @notes.present?
                  - @notes.each do |note|
                    .row
                      .col-lg-9.col-md-10.col-sm-12
                        .note
                          .note_content.col-lg-8.col-md-12
                            %p.info.mb-0
                              = "Class #{note.grade.name.humanize} #{note.category.name.humanize} •"
                              = pluralize(note.view, "Read")
                            = link_to note do
                              %h3.title.my-1= note.title
                              %p.body.mb-1
                                = truncate sanitize(note.body, tags: ['<h1>', '<h2>', '<h3>', '<a>', '<p>', '<span>', '<div>', '<img>']), length: 250 #truncate(strip_tags(note.body), length: 170)
                          .note_image.col-lg-4.col-md-12.d-none.d-lg-block
                            = link_to (image_tag note.image.url(:small)), note, class: 'img-note'
                      .col-lg-3.col-md-2.col-sm-12
                        - if current_user.present?
                          - if note.user == current_user or current_user.admin?
                            %p.status.mb-3
                              = note.is_verified ? "Verified" : "Not Verified"
                              = '•'
                              = note.status.humanize
                        - if can? :update, note
                          = link_to "Edit", edit_note_path(note), class: "btn-sm"
                        - if can? :destroy, note
                          = link_to "Delete", note_path(note), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-sm delete"
                  .pagination-nav.pt-4
                    = will_paginate @notes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center), previous_label: '&laquo;', next_label: '&raquo;', inner_window: 1, outer_window: 0
                - else
                  %p.no-property No notes added yet.
          .space