config/routes.rb
Rails.application.routes.draw do

  get '/sitemap', to: redirect("https://#{ENV.fetch('S3_BUCKET_NAME')}.s3.amazonaws.com/sitemaps/sitemap.xml.gz")

  %w[about faqs affiliate_program terms privacy creator_appeal admin_action apply].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users' }
  get 'users/show'
  resources :users do
    resources :categorizations
    member do
      get :following, :followers
      get "change_role",  to: "users#change_role"
    end
  end
  resources :relationships
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  get 'search', to: 'searches#search'
  get 'home', to: 'notes#home'
  resources :notes do
    collection do
      post :import
    end
    member do
      put "thank", to: "notes#vote"
      get "suggest", to: "notes#suggest"
      get "verify", to: "notes#verify"
      get "request_verification",  to: "notes#request_verification"
    end
    resources :questions, only: [:create, :destroy] do
      resources :answers, only: [:create, :destroy]
    end
  end
  resources :questions do
    member do
      put "vote", to: "questions#vote"
    end
    resources :answers, only: [:create, :edit, :update, :destroy] do
      put "vote", to: "answers#vote"
    end
  end
  resources :images, only: [:create, :destroy]
  root 'notes#home'
end

app/views/layouts/_footer.html.haml

%footer#footer
  .container.clearfix
    .app-info-row.row
      %ul.links.list-style-none.d-block.col-12.justify-content-center.mb-2.mb-lg-0
        %li.link-item
          %a{:href => 'https://www.facebook.com/mattrabcommunity', :target => '_blank'} © 2021 Mattrab Community.
        %li.link-item= link_to 'Privacy.', privacy_path
        %li.link-item= link_to 'Terms & Conditions.', terms_path
        %li.link-item= link_to 'Affiliate Program.', affiliate_program_path
        %li.link-item= link_to 'About Mattrab.', about_path
        %li.link-item= link_to 'FAQs and Help.', faqs_path if !user_signed_in?

app/views/layouts/_header.html.haml
%header.main
  .container.clearfix
    .row
      .col-3.col-sm-3.col-md-8.d-flex.justify-content-start
        %a.nav-brand{:href => root_path}
          %span.d-none.d-md-inline= 'ask'
          mattrab
        .search-at-nav.justify-content-start.d-none.d-md-block
          %a.nav-link.d-inline-block.d-md-none.btn-action.search-toggle
            %i.fa.fa-arrow-left
          %form.ml-2{:action => "/search"}
            %input.ask-ah{"aria-label" => "Search", :placeholder => "Your question or any topic", :name => "query", :type => "search"}
            %button.submit{:type => "submit"}
              %i.fa.fa-search
      .col-9.col-sm-9.col-md-4.d-flex.justify-content-end
        %ul.nav.justify-content-end
          %li.nav-item.d-block.d-md-none
            %a.nav-link.btn-action.search-toggle
              %i.fa.fa-search
          - unless current_page?(root_path) or  current_page?(home_path)
            %li.nav-item
              %a.trigger-browse.btn-action.nav-link{"data-toggle" => "modal", :href => "#browse"}
                %i.fa.fa-book.d-md-inline.d-lg-none
                %span.d-none.d-lg-inline= 'Browse'
          - if !user_signed_in?
            %li.nav-item
              = link_to new_user_session_path, class: 'btn-action nav-link' do
                %i.fa.fa-sign-in-alt.d-md-inline.d-lg-none
                %span.d-none.d-lg-inline= 'Log In'
            %li.nav-item
              %a.trigger-sign-in.btn-action.nav-link{"data-toggle" => "modal", :href => "#sign-in"}
                %i.fa.fa-user-plus.d-md-inline.d-lg-none
                %span.d-none.d-lg-inline= 'Sign Up'
          - else
            %li.nav-item.btn-group.dropdown.cdropdown
              %a.nav-link.btn-action.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button",  "data-offset" => "0,8" }
                %i.fa.fa-plus.d-md-inline.d-lg-none
                %span.d-none.d-lg-inline= 'Create'
              .dropdown-menu.dropdown-menu-right
                - if can? :create, Note
                  = link_to new_note_path, class: 'dropdown-item' do
                    %i.fas.fa-sticky-note
                    Note
                - else
                  = link_to creator_appeal_path, class: 'dropdown-item' do
                    %i.fas.fa-sticky-note
                    Note
                = link_to new_question_path, class: 'dropdown-item' do
                  %i.fas.fa-comment-alt
                  Question
            %li.nav-item.btn-group.dropdown.ndropdown{"data-behavior" => "notifications"}
              %a.nav-link.dropdown-toggle{"data-behavior" => "open-n", "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button",  "data-offset" => "0,8" }
                %i.fa.fa-bell
                %span.count{"data-behavior" => "unread-count"}
              .dropdown-menu.dropdown-menu-right
                %p.this-head.mb-0
                  = 'Notifications'
                  = link_to "Mark all as read", current_user, class: 'mark pull-right'
                .dropdown-divider.mb-1
                %p.this-type.mb-0= 'NEW'
                .dropdown-divider.mt-1
                .new-notifications{"data-behavior" => "new-notification-items"}

                .dropdown-divider.mb-1
                %p.this-type.mb-0= 'EARLIER'
                .dropdown-divider.mt-1
                .earlier-notifications{"data-behavior" => "earlier-notification-items"}

            %li.nav-item.btn-group.dropdown.udropdown
              %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button",  "data-offset" => "0,8" }
                = image_tag current_user.avatar_address(:small)
              .dropdown-menu.dropdown-menu-right
                %p.nav-user-name.mb-0= current_user.name
                %p.nav-user-email.mb-0= current_user.email
                .dropdown-divider
                = link_to "My Library", current_user, class: 'dropdown-item'
                = link_to "My Questions", user_path(current_user, :tab => :question), class: 'dropdown-item' if current_user.creator? or current_user.admin? or current_user.superadmin?
                .dropdown-divider
                = link_to "FAQs and Help", faqs_path, class: 'dropdown-item'
                = link_to "Settings", edit_user_registration_path, class: 'dropdown-item'
                = link_to "Log Out", destroy_user_session_path, method: :delete, class: 'dropdown-item'

#sign-in.sing-in-modal
  .sign-in-content
    %a.close-sign-in{"data-toggle" => "modal", :href => "#sign-in"}
      %i.fas.fa-times
    = link_to 'Log in with email', new_user_session_path, class: 'sign-in-action with-email'
    = link_to 'Sign up with email', new_user_registration_path, class: 'sign-up-action with-email'
    %span or
    = link_to user_google_oauth2_omniauth_authorize_path, "data-turbolinks" => false, class: 'sign-in-action with-google' do
      %i.fab.fa-google
      Log in with Google
- unless current_page?(root_path) or  current_page?(home_path)
  #browse.browse-modal
    .container
      %a.close-browse{"data-toggle" => "modal", :href => "#browse"}
        %i.fas.fa-times
      .row.browse-content
        - Grade.all.each do |grade|
          .col-6.col-md-3.mb-4
            %h4.grade-name= grade.name.humanize
            %ul.chapters
              - grade.categories.each do |category|
                %li.category-item= link_to category.name.humanize, notes_url(:grade=>"#{grade.name}", :category=>"#{category.name}", :chapter=>"#{category.chapters.first.try(:id)}")

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    = csrf_meta_tags
    = display_meta_tags(default_meta_tags)
    = favicon_link_tag 'favicon.ico', rel: 'icon', type: 'image/ico'

    = stylesheet_link_tag "/manifest.json", rel: 'manifest'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
    = stylesheet_link_tag "https://use.fontawesome.com/releases/v5.12.0/css/all.css", crossorigin: "anonymous", integrity: "sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M"
    %script{:async => "", "data-ad-client" => "ca-pub-8740559156368061", :src => "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
    %meta{:name => "google-site-verification", :content => "hFEpZ1lvpst_QL9-WkObIRbzM7B_hsoOC5Hg2k4gdvw"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{:content => "default", :name => "apple-mobile-web-app-status-bar-style"}
    %meta{content: "en", "http-equiv" => "Content-Language"}

    = favicon_link_tag 'icons/mattrab-57x57.png', rel: 'apple-touch-icon', sizes: '57x57'
    = favicon_link_tag 'icons/mattrab-60x60.png', rel: 'apple-touch-icon', sizes: '60x60'
    = favicon_link_tag 'icons/mattrab-72x72.png', rel: 'apple-touch-icon', sizes: '72x72'
    = favicon_link_tag 'icons/mattrab-76x76.png', rel: 'apple-touch-icon', sizes: '76x76'
    = favicon_link_tag 'icons/mattrab-114x114.png', rel: 'apple-touch-icon', sizes: '114x114'
    = favicon_link_tag 'icons/mattrab-120x120.png', rel: 'apple-touch-icon', sizes: '120x120'
    = favicon_link_tag 'icons/mattrab-114x114.png', rel: 'apple-touch-icon', sizes: '114x114'
    = favicon_link_tag 'icons/mattrab-152x152.png', rel: 'apple-touch-icon', sizes: '152x152'
    = favicon_link_tag 'icons/mattrab-180x180.png', rel: 'apple-touch-icon', sizes: '180x180'

  %body

    = render "layouts/header"
    .header-space
    = yield
    = render "layouts/footer"

    -# Badge Code - Do Not Change The Code
    -# :javascript
    -#   document.write("<script type='text/javascript' src='https://visitorshitcounter.com/js/hitCounter.js?v="+Date.now()+"'><\/script>");
    -# Badge Code End Here

    - if notice
      .this-popup
        %i.fa.fa-times-circle.close-popup{:onclick => "this.parentElement.style.display='none';"}
        .popup-head
          %h3.popup-title
            %i.fa.fa-exclamation-circle
            = 'Notice'
        .popup-body
          %p.notice= notice
    - elsif alert
      .this-popup
        %i.fa.fa-times-circle.close-popup{:onclick => "this.parentElement.style.display='none';"}
        .popup-head
          %h3.popup-title
            %i.fa.fa-exclamation-triangle
            = 'Alert'
        .popup-body
          %p.notice= alert